# Generated by Django 3.1 on 2020-11-26 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('student_no', models.CharField(blank=True, max_length=6, verbose_name='Student Number')),
                ('grade', models.CharField(blank=True, choices=[('9th', '9th grade'), ('10th', '10th grade'), ('11th', '11th grade'), ('12th', '12th grade')], max_length=4, verbose_name='Grade')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
